// <auto-generated/>

namespace TileDB.Interop
{
    internal enum tiledb_data_order_t
    {
        TILEDB_UNORDERED_DATA = 0,
        TILEDB_INCREASING_DATA = 1,
        TILEDB_DECREASING_DATA = 2,
    }
}
