// <auto-generated/>

using System;
using TileDB.CSharp;

namespace TileDB.Interop
{
    [Obsolete(Obsoletions.TileDBInteropMessage + " Use the TileDB.CSharp.VfsMode type instead.", DiagnosticId = Obsoletions.TileDBInteropDiagId, UrlFormat = Obsoletions.SharedUrlFormat)]
    public enum tiledb_vfs_mode_t
    {
        TILEDB_VFS_READ = 0,
        TILEDB_VFS_WRITE = 1,
        TILEDB_VFS_APPEND = 2,
    }
}
