// <auto-generated/>

using System;
using TileDB.CSharp;

namespace TileDB.Interop
{
    [Obsolete(Obsoletions.TileDBInteropMessage + " Use the TileDB.CSharp.ObjectType type instead.", DiagnosticId = Obsoletions.TileDBInteropDiagId, UrlFormat = Obsoletions.SharedUrlFormat)]
    public enum tiledb_object_t
    {
        TILEDB_INVALID = 0,
        TILEDB_GROUP = 1,
        TILEDB_ARRAY = 2,
    }
}
