// <auto-generated/>

using System;
using TileDB.CSharp;

namespace TileDB.Interop
{
    [Obsolete(Obsoletions.TileDBInteropMessage + " Use the TileDB.CSharp.WebpInputFormat type instead.", DiagnosticId = Obsoletions.TileDBInteropDiagId, UrlFormat = Obsoletions.SharedUrlFormat)]
    public enum tiledb_filter_webp_format_t
    {
        TILEDB_WEBP_NONE = 0,
        TILEDB_WEBP_RGB = 1,
        TILEDB_WEBP_BGR = 2,
        TILEDB_WEBP_RGBA = 3,
        TILEDB_WEBP_BGRA = 4,
    }
}
