// <auto-generated/>

using System;
using TileDB.CSharp;

namespace TileDB.Interop
{
    [Obsolete(Obsoletions.TileDBInteropMessage + " Use the TileDB.CSharp.WalkOrder type instead.", DiagnosticId = Obsoletions.TileDBInteropDiagId, UrlFormat = Obsoletions.SharedUrlFormat)]
    public enum tiledb_walk_order_t
    {
        TILEDB_PREORDER = 0,
        TILEDB_POSTORDER = 1,
    }
}
