// <auto-generated/>

using System;
using TileDB.CSharp;

namespace TileDB.Interop
{
    [Obsolete(Obsoletions.TileDBInteropMessage + " Use the TileDB.CSharp.EncryptionType type instead.", DiagnosticId = Obsoletions.TileDBInteropDiagId, UrlFormat = Obsoletions.SharedUrlFormat)]
    public enum tiledb_encryption_type_t
    {
        TILEDB_NO_ENCRYPTION = 0,
        TILEDB_AES_256_GCM = 1,
    }
}
