// <auto-generated/>

using System;
using System.ComponentModel;
using TileDB.CSharp;

namespace TileDB.Interop
{
    [Obsolete(Obsoletions.TileDBInterop3Message, DiagnosticId = Obsoletions.TileDBInterop3DiagId, UrlFormat = Obsoletions.SharedUrlFormat)]
    [EditorBrowsable(EditorBrowsableState.Never)]
    public enum tiledb_datatype_t
    {
        TILEDB_INT32 = 0,
        TILEDB_INT64 = 1,
        TILEDB_FLOAT32 = 2,
        TILEDB_FLOAT64 = 3,
        TILEDB_CHAR = 4,
        TILEDB_INT8 = 5,
        TILEDB_UINT8 = 6,
        TILEDB_INT16 = 7,
        TILEDB_UINT16 = 8,
        TILEDB_UINT32 = 9,
        TILEDB_UINT64 = 10,
        TILEDB_STRING_ASCII = 11,
        TILEDB_STRING_UTF8 = 12,
        TILEDB_STRING_UTF16 = 13,
        TILEDB_STRING_UTF32 = 14,
        TILEDB_STRING_UCS2 = 15,
        TILEDB_STRING_UCS4 = 16,
        TILEDB_ANY = 17,
        TILEDB_DATETIME_YEAR = 18,
        TILEDB_DATETIME_MONTH = 19,
        TILEDB_DATETIME_WEEK = 20,
        TILEDB_DATETIME_DAY = 21,
        TILEDB_DATETIME_HR = 22,
        TILEDB_DATETIME_MIN = 23,
        TILEDB_DATETIME_SEC = 24,
        TILEDB_DATETIME_MS = 25,
        TILEDB_DATETIME_US = 26,
        TILEDB_DATETIME_NS = 27,
        TILEDB_DATETIME_PS = 28,
        TILEDB_DATETIME_FS = 29,
        TILEDB_DATETIME_AS = 30,
        TILEDB_TIME_HR = 31,
        TILEDB_TIME_MIN = 32,
        TILEDB_TIME_SEC = 33,
        TILEDB_TIME_MS = 34,
        TILEDB_TIME_US = 35,
        TILEDB_TIME_NS = 36,
        TILEDB_TIME_PS = 37,
        TILEDB_TIME_FS = 38,
        TILEDB_TIME_AS = 39,
        TILEDB_BLOB = 40,
        TILEDB_BOOL = 41,
        TILEDB_GEOM_WKB = 42,
        TILEDB_GEOM_WKT = 43,
    }
}
