// <auto-generated/>

namespace TileDB.Interop
{
    internal unsafe partial struct tiledb_range_t
    {
        [NativeTypeName("const void *")]
        public void* min;

        [NativeTypeName("uint64_t")]
        public ulong min_size;

        [NativeTypeName("const void *")]
        public void* max;

        [NativeTypeName("uint64_t")]
        public ulong max_size;
    }
}
