// <auto-generated/>

using System;
using System.ComponentModel;
using TileDB.CSharp;

namespace TileDB.Interop
{
    internal enum tiledb_array_type_t
    {
        TILEDB_DENSE = 0,
        TILEDB_SPARSE = 1,
    }
}
