// <auto-generated/>

namespace TileDB.Interop
{
    internal enum tiledb_field_origin_t
    {
        TILEDB_ATTRIBUTE_FIELD = 0,
        TILEDB_DIMENSION_FIELD,
        TILEDB_AGGREGATE_FIELD,
    }
}
