version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      mstest:
        # Update MSTest packages together, they are sometimes incompatible with each other.
        patterns: ["MSTest.*"]
