# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- none

stages:
  - stage: CI
    condition: and(not(startsWith(variables['Build.SourceBranch'], 'refs/tags')), not(startsWith(variables['Build.SourceBranchName'], 'build-')))
    variables:
      BACKWARDS_COMPATIBILITY_ARRAYS: OFF
    jobs:
    - job: Windows
      strategy:
        matrix:
          VS2017:
            imageName: 'vs2017-win2016'
            TILEDB_S3: ON
      pool:
        vmImage: $(imageName)
      steps:
      - template: ci/azure-windows.yml
    - job: Linux
      timeoutInMinutes: 90
      strategy:
        matrix:
          linux_asan:
            imageName: 'ubuntu-20.04'
            TILEDB_S3: ON
            TILEDB_SERIALIZATION: ON
            CXX: g++
            CC: gcc

      pool:
        vmImage: $(imageName)
      steps:
      - template: ci/azure-linux.yml
    - job: macOS
      timeoutInMinutes: 90
      strategy:
        matrix:
          macOS_azure:
            imageName: 'macOS-10.15'
            TILEDB_S3: ON
            TILEDB_SERIALIZATION: ON
            CXX: clang++
            ARTIFACT_OS: macOS_azure
      pool:
        vmImage: $(imageName)
      steps:
      - template: ci/azure-mac.yml   