//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace tiledb {

public enum tiledb_encryption_type_t {
  TILEDB_NO_ENCRYPTION = 0,
  TILEDB_AES_256_GCM = 1
}

}
