//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace tiledb {

public enum tiledb_vfs_mode_t {
  TILEDB_VFS_READ = 0,
  TILEDB_VFS_WRITE = 1,
  TILEDB_VFS_APPEND = 2
}

}
