//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace tiledb {

public enum tiledb_layout_t {
  TILEDB_ROW_MAJOR = 0,
  TILEDB_COL_MAJOR = 1,
  TILEDB_GLOBAL_ORDER = 2,
  TILEDB_UNORDERED = 3
}

}
