//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace TileDB {

public class PairFloat32Float32 : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PairFloat32Float32(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PairFloat32Float32 obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~PairFloat32Float32() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          tiledbcsPINVOKE.delete_PairFloat32Float32(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public PairFloat32Float32() : this(tiledbcsPINVOKE.new_PairFloat32Float32__SWIG_0(), true) {
  }

  public PairFloat32Float32(float first, float second) : this(tiledbcsPINVOKE.new_PairFloat32Float32__SWIG_1(first, second), true) {
  }

  public PairFloat32Float32(PairFloat32Float32 other) : this(tiledbcsPINVOKE.new_PairFloat32Float32__SWIG_2(PairFloat32Float32.getCPtr(other)), true) {
    if (tiledbcsPINVOKE.SWIGPendingException.Pending) throw tiledbcsPINVOKE.SWIGPendingException.Retrieve();
  }

  public float first {
    set {
      tiledbcsPINVOKE.PairFloat32Float32_first_set(swigCPtr, value);
    } 
    get {
      float ret = tiledbcsPINVOKE.PairFloat32Float32_first_get(swigCPtr);
      return ret;
    } 
  }

  public float second {
    set {
      tiledbcsPINVOKE.PairFloat32Float32_second_set(swigCPtr, value);
    } 
    get {
      float ret = tiledbcsPINVOKE.PairFloat32Float32_second_get(swigCPtr);
      return ret;
    } 
  }

}

}
