//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace TileDB {

public class VectorOfVectorFloat32 : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IEnumerable<VectorFloat32>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VectorOfVectorFloat32(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VectorOfVectorFloat32 obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~VectorOfVectorFloat32() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          tiledbcsPINVOKE.delete_VectorOfVectorFloat32(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public VectorOfVectorFloat32(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (VectorFloat32 element in c) {
      this.Add(element);
    }
  }

  public VectorOfVectorFloat32(global::System.Collections.Generic.IEnumerable<VectorFloat32> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (VectorFloat32 element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public VectorFloat32 this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(VectorFloat32[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(VectorFloat32[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, VectorFloat32[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public VectorFloat32[] ToArray() {
    VectorFloat32[] array = new VectorFloat32[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<VectorFloat32> global::System.Collections.Generic.IEnumerable<VectorFloat32>.GetEnumerator() {
    return new VectorOfVectorFloat32Enumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new VectorOfVectorFloat32Enumerator(this);
  }

  public VectorOfVectorFloat32Enumerator GetEnumerator() {
    return new VectorOfVectorFloat32Enumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class VectorOfVectorFloat32Enumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<VectorFloat32>
  {
    private VectorOfVectorFloat32 collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public VectorOfVectorFloat32Enumerator(VectorOfVectorFloat32 collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public VectorFloat32 Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (VectorFloat32)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public void Clear() {
    tiledbcsPINVOKE.VectorOfVectorFloat32_Clear(swigCPtr);
  }

  public void Add(VectorFloat32 x) {
    tiledbcsPINVOKE.VectorOfVectorFloat32_Add(swigCPtr, VectorFloat32.getCPtr(x));
    if (tiledbcsPINVOKE.SWIGPendingException.Pending) throw tiledbcsPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = tiledbcsPINVOKE.VectorOfVectorFloat32_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = tiledbcsPINVOKE.VectorOfVectorFloat32_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    tiledbcsPINVOKE.VectorOfVectorFloat32_reserve(swigCPtr, n);
  }

  public VectorOfVectorFloat32() : this(tiledbcsPINVOKE.new_VectorOfVectorFloat32__SWIG_0(), true) {
  }

  public VectorOfVectorFloat32(VectorOfVectorFloat32 other) : this(tiledbcsPINVOKE.new_VectorOfVectorFloat32__SWIG_1(VectorOfVectorFloat32.getCPtr(other)), true) {
    if (tiledbcsPINVOKE.SWIGPendingException.Pending) throw tiledbcsPINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorOfVectorFloat32(int capacity) : this(tiledbcsPINVOKE.new_VectorOfVectorFloat32__SWIG_2(capacity), true) {
    if (tiledbcsPINVOKE.SWIGPendingException.Pending) throw tiledbcsPINVOKE.SWIGPendingException.Retrieve();
  }

  private VectorFloat32 getitemcopy(int index) {
    VectorFloat32 ret = new VectorFloat32(tiledbcsPINVOKE.VectorOfVectorFloat32_getitemcopy(swigCPtr, index), true);
    if (tiledbcsPINVOKE.SWIGPendingException.Pending) throw tiledbcsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private VectorFloat32 getitem(int index) {
    VectorFloat32 ret = new VectorFloat32(tiledbcsPINVOKE.VectorOfVectorFloat32_getitem(swigCPtr, index), false);
    if (tiledbcsPINVOKE.SWIGPendingException.Pending) throw tiledbcsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, VectorFloat32 val) {
    tiledbcsPINVOKE.VectorOfVectorFloat32_setitem(swigCPtr, index, VectorFloat32.getCPtr(val));
    if (tiledbcsPINVOKE.SWIGPendingException.Pending) throw tiledbcsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(VectorOfVectorFloat32 values) {
    tiledbcsPINVOKE.VectorOfVectorFloat32_AddRange(swigCPtr, VectorOfVectorFloat32.getCPtr(values));
    if (tiledbcsPINVOKE.SWIGPendingException.Pending) throw tiledbcsPINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorOfVectorFloat32 GetRange(int index, int count) {
    global::System.IntPtr cPtr = tiledbcsPINVOKE.VectorOfVectorFloat32_GetRange(swigCPtr, index, count);
    VectorOfVectorFloat32 ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorOfVectorFloat32(cPtr, true);
    if (tiledbcsPINVOKE.SWIGPendingException.Pending) throw tiledbcsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, VectorFloat32 x) {
    tiledbcsPINVOKE.VectorOfVectorFloat32_Insert(swigCPtr, index, VectorFloat32.getCPtr(x));
    if (tiledbcsPINVOKE.SWIGPendingException.Pending) throw tiledbcsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, VectorOfVectorFloat32 values) {
    tiledbcsPINVOKE.VectorOfVectorFloat32_InsertRange(swigCPtr, index, VectorOfVectorFloat32.getCPtr(values));
    if (tiledbcsPINVOKE.SWIGPendingException.Pending) throw tiledbcsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    tiledbcsPINVOKE.VectorOfVectorFloat32_RemoveAt(swigCPtr, index);
    if (tiledbcsPINVOKE.SWIGPendingException.Pending) throw tiledbcsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    tiledbcsPINVOKE.VectorOfVectorFloat32_RemoveRange(swigCPtr, index, count);
    if (tiledbcsPINVOKE.SWIGPendingException.Pending) throw tiledbcsPINVOKE.SWIGPendingException.Retrieve();
  }

  public static VectorOfVectorFloat32 Repeat(VectorFloat32 value, int count) {
    global::System.IntPtr cPtr = tiledbcsPINVOKE.VectorOfVectorFloat32_Repeat(VectorFloat32.getCPtr(value), count);
    VectorOfVectorFloat32 ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorOfVectorFloat32(cPtr, true);
    if (tiledbcsPINVOKE.SWIGPendingException.Pending) throw tiledbcsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    tiledbcsPINVOKE.VectorOfVectorFloat32_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    tiledbcsPINVOKE.VectorOfVectorFloat32_Reverse__SWIG_1(swigCPtr, index, count);
    if (tiledbcsPINVOKE.SWIGPendingException.Pending) throw tiledbcsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, VectorOfVectorFloat32 values) {
    tiledbcsPINVOKE.VectorOfVectorFloat32_SetRange(swigCPtr, index, VectorOfVectorFloat32.getCPtr(values));
    if (tiledbcsPINVOKE.SWIGPendingException.Pending) throw tiledbcsPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
