//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace TileDB {

public class VectorOfVectorDouble : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IEnumerable<VectorDouble>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VectorOfVectorDouble(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VectorOfVectorDouble obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~VectorOfVectorDouble() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          tiledbcsPINVOKE.delete_VectorOfVectorDouble(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public VectorOfVectorDouble(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (VectorDouble element in c) {
      this.Add(element);
    }
  }

  public VectorOfVectorDouble(global::System.Collections.Generic.IEnumerable<VectorDouble> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (VectorDouble element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public VectorDouble this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(VectorDouble[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(VectorDouble[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, VectorDouble[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public VectorDouble[] ToArray() {
    VectorDouble[] array = new VectorDouble[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<VectorDouble> global::System.Collections.Generic.IEnumerable<VectorDouble>.GetEnumerator() {
    return new VectorOfVectorDoubleEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new VectorOfVectorDoubleEnumerator(this);
  }

  public VectorOfVectorDoubleEnumerator GetEnumerator() {
    return new VectorOfVectorDoubleEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class VectorOfVectorDoubleEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<VectorDouble>
  {
    private VectorOfVectorDouble collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public VectorOfVectorDoubleEnumerator(VectorOfVectorDouble collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public VectorDouble Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (VectorDouble)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public void Clear() {
    tiledbcsPINVOKE.VectorOfVectorDouble_Clear(swigCPtr);
  }

  public void Add(VectorDouble x) {
    tiledbcsPINVOKE.VectorOfVectorDouble_Add(swigCPtr, VectorDouble.getCPtr(x));
    if (tiledbcsPINVOKE.SWIGPendingException.Pending) throw tiledbcsPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = tiledbcsPINVOKE.VectorOfVectorDouble_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = tiledbcsPINVOKE.VectorOfVectorDouble_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    tiledbcsPINVOKE.VectorOfVectorDouble_reserve(swigCPtr, n);
  }

  public VectorOfVectorDouble() : this(tiledbcsPINVOKE.new_VectorOfVectorDouble__SWIG_0(), true) {
  }

  public VectorOfVectorDouble(VectorOfVectorDouble other) : this(tiledbcsPINVOKE.new_VectorOfVectorDouble__SWIG_1(VectorOfVectorDouble.getCPtr(other)), true) {
    if (tiledbcsPINVOKE.SWIGPendingException.Pending) throw tiledbcsPINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorOfVectorDouble(int capacity) : this(tiledbcsPINVOKE.new_VectorOfVectorDouble__SWIG_2(capacity), true) {
    if (tiledbcsPINVOKE.SWIGPendingException.Pending) throw tiledbcsPINVOKE.SWIGPendingException.Retrieve();
  }

  private VectorDouble getitemcopy(int index) {
    VectorDouble ret = new VectorDouble(tiledbcsPINVOKE.VectorOfVectorDouble_getitemcopy(swigCPtr, index), true);
    if (tiledbcsPINVOKE.SWIGPendingException.Pending) throw tiledbcsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private VectorDouble getitem(int index) {
    VectorDouble ret = new VectorDouble(tiledbcsPINVOKE.VectorOfVectorDouble_getitem(swigCPtr, index), false);
    if (tiledbcsPINVOKE.SWIGPendingException.Pending) throw tiledbcsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, VectorDouble val) {
    tiledbcsPINVOKE.VectorOfVectorDouble_setitem(swigCPtr, index, VectorDouble.getCPtr(val));
    if (tiledbcsPINVOKE.SWIGPendingException.Pending) throw tiledbcsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(VectorOfVectorDouble values) {
    tiledbcsPINVOKE.VectorOfVectorDouble_AddRange(swigCPtr, VectorOfVectorDouble.getCPtr(values));
    if (tiledbcsPINVOKE.SWIGPendingException.Pending) throw tiledbcsPINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorOfVectorDouble GetRange(int index, int count) {
    global::System.IntPtr cPtr = tiledbcsPINVOKE.VectorOfVectorDouble_GetRange(swigCPtr, index, count);
    VectorOfVectorDouble ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorOfVectorDouble(cPtr, true);
    if (tiledbcsPINVOKE.SWIGPendingException.Pending) throw tiledbcsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, VectorDouble x) {
    tiledbcsPINVOKE.VectorOfVectorDouble_Insert(swigCPtr, index, VectorDouble.getCPtr(x));
    if (tiledbcsPINVOKE.SWIGPendingException.Pending) throw tiledbcsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, VectorOfVectorDouble values) {
    tiledbcsPINVOKE.VectorOfVectorDouble_InsertRange(swigCPtr, index, VectorOfVectorDouble.getCPtr(values));
    if (tiledbcsPINVOKE.SWIGPendingException.Pending) throw tiledbcsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    tiledbcsPINVOKE.VectorOfVectorDouble_RemoveAt(swigCPtr, index);
    if (tiledbcsPINVOKE.SWIGPendingException.Pending) throw tiledbcsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    tiledbcsPINVOKE.VectorOfVectorDouble_RemoveRange(swigCPtr, index, count);
    if (tiledbcsPINVOKE.SWIGPendingException.Pending) throw tiledbcsPINVOKE.SWIGPendingException.Retrieve();
  }

  public static VectorOfVectorDouble Repeat(VectorDouble value, int count) {
    global::System.IntPtr cPtr = tiledbcsPINVOKE.VectorOfVectorDouble_Repeat(VectorDouble.getCPtr(value), count);
    VectorOfVectorDouble ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorOfVectorDouble(cPtr, true);
    if (tiledbcsPINVOKE.SWIGPendingException.Pending) throw tiledbcsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    tiledbcsPINVOKE.VectorOfVectorDouble_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    tiledbcsPINVOKE.VectorOfVectorDouble_Reverse__SWIG_1(swigCPtr, index, count);
    if (tiledbcsPINVOKE.SWIGPendingException.Pending) throw tiledbcsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, VectorOfVectorDouble values) {
    tiledbcsPINVOKE.VectorOfVectorDouble_SetRange(swigCPtr, index, VectorOfVectorDouble.getCPtr(values));
    if (tiledbcsPINVOKE.SWIGPendingException.Pending) throw tiledbcsPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
