//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace TileDB {

public enum tiledb_query_status_t {
  TILEDB_FAILED = 0,
  TILEDB_COMPLETED = 1,
  TILEDB_INPROGRESS = 2,
  TILEDB_INCOMPLETE = 3,
  TILEDB_UNINITIALIZED = 4
}

}
