//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace TileDB {

public enum tiledb_object_t {
  TILEDB_INVALID = 0,
  TILEDB_GROUP = 1,
  TILEDB_ARRAY = 2
}

}
