//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace TileDB {

public enum tiledb_filesystem_t {
  TILEDB_HDFS = 0,
  TILEDB_S3 = 1,
  TILEDB_AZURE = 2,
  TILEDB_GCS = 3
}

}
